// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhspphsdtmmgbtfpsvlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoc3BwaHNkdG1tZ2J0ZnBzdmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDc0NjMsImV4cCI6MjA2MDA4MzQ2M30.Jp0WpUrsRZaclU5rk93u1q5w1MteXNN0B0w7-rEiFGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);